config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :donations, only: [:create]
    resources :reviews, only: [:create]
  end
  devise_for :users
  resources :projects, only: [:index, :show]
  # resources :pages, only: [:show]
  root to: 'pages#home'
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
    get 'articles/:article_id/reviews', to:'reviews#index'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :users, through: :donations
  has_many :donations, dependent: :nullify
  has_many :reviews, dependent: :destroy
  belongs_to :project
  validates :title, :subtitle, :summary, :content, :picture, :category, presence: true
  validates :summary, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }
  CATEGORIES = ["politics","culture","europe","food","fashion"]
  validates :category, inclusion: { in: CATEGORIES}
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :amount, inclusion: { in: (1..10000).to_a.map { |number| number/10.0 } }, numericality: true
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, :description, :picture, presence:true
  has_many :articles
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :rating, presence:true
  validates :rating, inclusion: { in: [0,1,2,3,4,5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :articles, through: :donations
  has_many :donations, dependent: :destroy
  has_many :reviews
  validates :bio, length: { maximum: 1000, too_long: "%{count} characters is the maximum allowed" }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/api/v1/base_controller.rb
# app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  include Pundit

  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from StandardError,                with: :internal_server_error
  rescue_from Pundit::NotAuthorizedError,   with: :user_not_authorized
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def user_not_authorized(exception)
    render json: {
      error: "Unauthorized #{exception.policy.class.to_s.underscore.camelize}.#{exception.query}"
    }, status: :unauthorized
  end

  def not_found(exception)
    render json: { error: exception.message }, status: :not_found
  end

  def internal_server_error(exception)
    if Rails.env.development?
      response = { type: exception.class.to_s, error: exception.message }
    else
      response = { error: "Internal Server Error" }
    end
    render json: response, status: :internal_server_error
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < Api::V1::BaseController

  def index
    @aritcle = Article.find(params[:article_id])
    authorize @article
    @reviews = policy_scope(Review).where(article: @article)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.where.not(latitude: nil, longitude: nil)
    @markers = @users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        icon: {
          url: user.picture, #
          scaledSize: {
            height: 50,
            width: 50
          }
        },
        style: {
          'border-radius': '50%'
        }
        # infoWindow: { content: render_to_string(partial: "/flats/map_box", locals: { flat: flat }) }
      }
    end

    if params[:query].present?
      @articles = policy_scope(Article).where("title ILIKE ?", "%#{params[:query]}%")
    else
      @articles = policy_scope(Article).order(created_at: :desc)
    end
  end

  def show
    @donation = Donation.new
    @review = Review.new
    @reviews = Review.where(article: @article)
    authorize @donation
  end

  def new
    @article = Article.new
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    authorize @article

    if @article.save
      redirect_to articles_path, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def edit
    authorize @article
  end

  def update
    authorize @article

    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @article
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def find_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :subtitle, :summary, :content, :picture, :category, :project_id, :publishing_date)
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_article

  def create
    @donation = Donation.new(donation_params)
    @donation.article = @article
    @donation.user = current_user
    authorize @donation
    if @donation.save
      redirect_to article_path(@article)
    else
      render 'articles/show'
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def donation_params
    params.require(:donation).permit(:amount)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :find_article, only: [:home]

  def home
  end

  private

  def find_article
    @articles = Article.last(3)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show]

  def index
    @projects = policy_scope(Project).order(created_at: :desc)
  end

  def show
    # @article = Article.where(project_id = @project.id & )
    authorize @project
  end

  private

  def find_project
    @project = Project.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_article, only: [:create]

  def create
    @donation = Donation.new
    @reviews = Review.where(article: @article)
    @review = Review.new(review_params)
    @review.article = @article # assignment in order to associate article with review
    @review.user = current_user
    authorize @review

    if @review.save
      redirect_to article_path(@article), notice: 'Review was successfully created.'
    else
      render 'articles/show', article: @article, reviews: @reviews, donation: @donation
      # render goes to View folder by default
      # should render the view with specific instances
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
<%= f.input :title, placeholder: "Title", label: false, input_html: { class: 'form_light no_border form_title' } %>
<%= f.input :subtitle, placeholder: "Subtitle", label: false, input_html: { class: 'form_light no_border form_subtitle margin_bottom' }%>
<div class='no_padding'>
  <%= f.input :content, placeholder: "Enter the content.", label: false, input_html: { class: 'quill_container no_padding_left' }%>
</div>
<%= f.input :summary, placeholder: "Summary", label: false, input_html: { class: 'form_light no_border' } %>
<%= f.input :picture, placeholder: "Picture's HTML", label: false, input_html: { class: 'form_light no_border' } %>
<div class="dropdown_wrapper">
<%= f.input :category, collection: Article::CATEGORIES, prompt: "Category", label: false, input_html: { class: 'form_light no_border no_padding' }%>
<%= f.association :project, prompt: "Choose a project to donate to", label: false, input_html: { class: 'form_light no_border' }%>
</div>
<%= f.button :submit, class: "btn btn-primary"  %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container-fluid">

  <div class="row margin-left">

    <div class="col-xs-7 col-md-7 col-sm-7">
    <h1 class="index-title">Articles</h1>
      <div class="row">
        <% @articles.each do |article| %>
          <div class="col-xs-12 col-sm-6">
            <div class="card-container">
              <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= article.picture %>);">
              </div>
              <div class="card-text grow">
                <div class="card-details">
                  <p> <%= article.category.upcase %></p>
                  <p class="top-right"><%= article.publishing_date %></p>
                </div>
                <div class="card-titles">
                  <h5><%= link_to truncate(article.title, length: 65), article_path(article) %></h5>
                  <p><%= truncate(article.subtitle, length: 40) %></p>
                </div>
                <div class="card-profile">
                  <div class="center">
                    <img class="card-user" src=<%= article.user.picture %>>
                  </div>
                  <div class="user-details">
                    <div>
                      <p> <b><%= article.user.first_name%> <%= article.user.last_name %></b> </p>
                    </div>
                    <div>
                      <p class="grow"> <%= article.user.address %></p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-xs-5 col-md-5 col-sm-5 sticky-div">
      <div
        id="map"
        style="width: 100%;
        height: 800px;"
        data-markers="<%= @markers.to_json %>" >
      </div>
    </div>

  </div>

</div>

app/views/articles/new.html.erb
<div class="white_background padding_bottom">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6  col-lg-8 col-sm-offset-3 col-lg-offset-2 align margin_bottom">
        <h1>New Article</h1>
        <h2 class="link_thin"><%= link_to 'Back', articles_path %></h2>
      </div>
      <div class="col-xs-12 col-sm-6  col-lg-8 col-sm-offset-3 col-lg-offset-2">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="article-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @article.picture %>);">
</div>

<div class="row margin-left">
  <div class="col-xs-7 col-md-7 col-sm-7">
    <div class="article-text margins">
      <div class="article-details">
        <p> <%= @article.category.upcase %></p>
        <p class="top-right"><%= @article.publishing_date %></p>
      </div>

        <h1><%= @article.title %></h1>
        <h5><%= @article.subtitle %></h5>
<hr>

        <h4>Summary</h4>
        <p> <%= @article.summary %></p>

      <div class="article-profile">

        <div class="center">
          <img class="card-user" src=<%= @article.user.picture %>>
        </div>

        <div class="user-details">

          <div>
            <p> <b><%= @article.user.first_name%> <%= @article.user.last_name %></b> </p>
          </div>

          <div>
            <p class="grow"> <%= @article.user.address %></p>
          </div>

        </div>
      </div>

      <div>

        <h4>Chosen project</h4>

        <img class="card-user" src=<%= @article.project.picture %>>
        <%= link_to @article.project.name, @article.project %>

      </div>

    </div>

    <% if Donation.find_by(user_id: current_user.id, article_id: @article.id) %>

      <div class="article-content">

        <h4>Full article</h4>

        <p><%= raw @article.content %></p>
        <h4>Review</h4>

          <div class="rating">
            <i class="glyphicon glyphicon-star-empty star-input" data-rating="1"></i>
            <i class="glyphicon glyphicon-star-empty star-input" data-rating="2"></i>
            <i class="glyphicon glyphicon-star-empty star-input" data-rating="3"></i>
            <i class="glyphicon glyphicon-star-empty star-input" data-rating="4"></i>
            <i class="glyphicon glyphicon-star-empty star-input" data-rating="5"></i>
          </div>

          <div id="simple-f">
            <%= simple_form_for [@article, @review] do |f| %>
            <%= f.input :rating, as: :hidden, id: "rating-hidden-input" %>
            <%= f.input :comment, placeholder: "Your review matters.", :input_html => { :rows => 7} %>
            <%= f.submit "Submit Review", class: "btn-blue" %>
            <% end %>
          </div>

      </div>

    <% end %>

    <hr>

    <% if @reviews.exists? %>

      <% @reviews.each do |review| %>

        <div class="article-profile">

          <div class="center">
            <img class="card-user" src=<%= review.user.picture %>>
          </div>

          <div class="user-details">

            <div>
              <p><b><%= review.user.first_name%> <%= review.user.last_name %></b></p>
            </div>
            <div>
              <p class="grow"> <%= review.user.address %></p>
            </div>

          </div>
        </div>

        <ul class="list-inline">
          <% review.rating.times do %>
            <li class="list-inline-item"><i class="glyphicon glyphicon-star"></i></li>
          <% end %>
          <% unless review.rating == 5 %>
            <% (5 - review.rating).times do %>
            <li class="list-inline-item"><i class="glyphicon glyphicon-star-empty"></i></li>
            <% end %>
          <% end %>
        </ul>

        <p><%= review.comment %></p>

        <hr>

      <% end %>

    <% end %>

    <div class="buttons">
      <%= link_to "Back", articles_path, class: "btn-gray" %>
    </div>

    <div class="buttons">

      <% if policy(@article).edit? %>
        <%= link_to "Edit", edit_article_path(@article), class: "btn-gray" %>
      <% end %>

      <% if policy(@article).destroy? %>
        <%= link_to "Delete", article_path(@article), class: "btn-gray", method: :delete, data: { confirm: "Are you sure?"} %>
      <% end %>

    </div>

  </div>

  <div class="col-xs-5 col-md-5 col-sm-5">

    <% if donation = Donation.find_by(user_id: current_user.id, article_id: @article.id) %>

      <h3>Donation</h3>
      <p><%= donation.amount %>€</p>
      <a href="#", class= "btn-blue-empty">Donation done</a>
      <h5> Thank you for your donation ! </h5>

    <% else %>

    <div>

      <h3>Donation</h3>
      <p>For <%= @article.project.name %></p>
      <%= simple_form_for [@article, @donation] do |f| %>
      <%= f.input :amount, placeholder: "0.10" %>
      <%= f.submit "Donate", class: "btn-blue" %>
      <% end %>

    </div>

    <% end %>

  </div>

</div>
<%= content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
        // Check Radio-box
      $(".star-input").click(function() {
        rate = $(this).data('rating');
        $("#rating-hidden-input");
      });
    });
  </script>
<% end %>

app/views/donations/new.html.erb
<h1>Donations#new</h1>
<p>Find me in app/views/donations/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Lora|Open+Sans" rel="stylesheet">
  <link rel="icon" href="<%= image_path("logo_blue.png") %>" type="image/png"/>
  <title>Nationall</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_pack_tag "map" %> <!-- add this line -->
  <%= yield(:after_js) %>
</body>
</html>

app/views/pages/home.html.erb
<div class="wrapper">

  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url(<%= image_url "national_top.jpg" %>);">

      <h1 class="title">NΔTIONΔLL</h1>

      <h2 class="center">Discover Europe</h2>

      <%= link_to "Read Articles", articles_path, class: "btn btn-success" %>
  </div>

  <br>

  <div class="row home-latest">
    <h2 class="articles-header">Latest articles</h2>
    <% @articles.each do |article| %>
      <div class="col-xs-12 col-md-6 col-lg-4">
        <div class="card-container">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= article.picture %>);">
          </div>
          <div class="card-text">
            <div class="card-details">
              <p> <%= article.category.upcase %></p>
              <p class="top-right"><%= article.publishing_date %></p>
            </div>
            <div class="card-titles">
              <h5><%= link_to article.title, article_path(article) %></h5>
              <p><%= truncate(article.subtitle, length: 40) %></p>
            </div>
            <div class="card-profile">
              <div class="center">
                <img class="card-user" src=<%= article.user.picture %>>
              </div>
              <div class="user-details">
                <div>
                  <p> <%= article.user.first_name%> <%= article.user.last_name %></p>
                </div>
                <div>
                  <p class="grow"> <%= article.user.address %></p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/projects/index.html.erb
<div class="container-fluid">

  <div class="row margin-left">

    <h1>Projects</h1>

    <div class="col-xs-7 col-sm-7">
    <% @projects.each do |project| %>
      <div class="horizontal-card card-container">
        <div>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= project.picture %>);">
          </div>
        </div>
        <div class="card-text grow">
          <div class="card-titles">
            <h5><%= link_to project.name, project_path(project) %></h5>
            <p><%= truncate(project.description, length: 150) %></p>
            <%= link_to "Link to the project website", project.url %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row margin-left">
  <div class="col-xs-7 col-md-7 col-sm-7">
  <h1>Project <%= @project.id %></h1>
    <div class="project-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= @project.picture %>);">
    </div>
    <div class="project-text margins">
      <h3><%= @project.name %></h3>
      <p> <%= @project.description %></p>
      <%= link_to @project.url %>
    </div>

    <div class="buttons">
      <%= link_to "Back", projects_path, class: "btn-gray" %>
    </div>

    <div class="buttons">
      <% if policy(@project).edit? %>
        <%= link_to "Edit", edit_project_path(@project), class: "btn-gray" %>
      <% end %>

      <% if policy(@project).destroy? %>
        <%= link_to "Delete", project_path(@project), class: "btn-gray", method: :delete, data: { confirm: "Are you sure?"} %>
      <% end %>
    </div>

  </div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <div class="navbar-left">
    <!-- Logo -->
    <%= link_to articles_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo_blue.png", height: 50 %>
    <% end %>

    <%= form_tag articles_path, method: :get, class: "navbar-wagon-search" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control navbar-search-input form_restaure_padding",
      placeholder: "Find an article..."
      %>
      <% end %>
    </div>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Write an article", new_article_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.picture %>
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </div>